
APP_INFO = {
    admad: {owner: '', alias: ''},
    admas: {owner: '', alias: ''},
    admsm: {owner: '', alias: ''},
    appad: {owner: '', alias: ''},
    appai: {owner: '', alias: ''},
    appar: {owner: '', alias: ''},
    appba: {owner: '', alias: ''},
    appbd: {owner: '', alias: ''},
    appbi: {owner: 'Christian Meusel', alias: 'Adeptia'},
    appbr: {owner: '', alias: ''},
    appbs: {owner: '', alias: ''},
    appbt: {owner: '', alias: ''},
    appbx: {owner: '', alias: ''},
    appcm: {owner: '', alias: ''},
    appdj: {owner: '', alias: ''},
    appdl: {owner: 'WebOps', alias: 'TruckScout Delta'},
    appds: {owner: 'Gunnar Ludwig', alias: 'AS24 Delta'},
    appdw: {owner: 'Sebastian Ullmann', alias: 'Salesforce'},
    appdy: {owner: '', alias: ''},
    appia: {owner: '', alias: ''},
    appib: {owner: '', alias: ''},
    appis: {owner: 'Sebastian Ullmann', alias: 'ISS'},
    appjo: {owner: '', alias: ''},
    appjs: {owner: '', alias: ''},
    appkm: {owner: '', alias: ''},
    appl7: {owner: 'Stephan Keidel/Christan Meusel', alias: 'Layer7'},
    appld: {owner: '', alias: ''},
    appma: {owner: '', alias: 'Mobile'},  # app + Linux = Web
    appmd: {owner: '', alias: ''},
    appmj: {owner: '', alias: ''},
    appms: {owner: '', alias: ''},
    appmw: {owner: '', alias: ''},
    appnj: {owner: '', alias: ''},
    apppj: {owner: '', alias: ''},
    apppp: {owner: '', alias: ''},
    appre: {owner: '', alias: ''},
    apprw: {owner: '', alias: ''},
    appsat: {owner: '', alias: ''},
    appsf: {owner: '', alias: ''},
    appsm: {owner: '', alias: ''},
    appst: {owner: 'Anja Beireuther', alias: 'Tot: Meine Stadt'},
    apptj: {owner: '', alias: ''},
    appvo: {owner: '', alias: ''},
    appwp: {owner: '', alias: ''},
    appwt: {owner: '', alias: ''},
    appwu: {owner: '', alias: ''},
    appxf: {owner: '', alias: ''},
    appyt: {owner: '', alias: ''},
    bakpu: {owner: '', alias: ''},
    cdncp: {owner: 'Alex Diegelmann', alias: 'CMS Picture Server'},
    cdncs: {owner: '', alias: ''},
    cdnds: {owner: '', alias: ''},
    cdnpi: {owner: '', alias: 'Picture Server'},
    cdnsc: {owner: 'Christian Rodemeyer', alias: 's.autoscout24.de', artifacts: '//dappbsv002/transfer/build_results/s.autoscout24.de'},
    cdnws: {owner: '', alias: ''},
    dcoas: {owner: '', alias: ''},
    dcoli: {owner: '', alias: ''},
    dcoop: {owner: '', alias: ''},
    dcosv: {owner: '', alias: ''},
    dcows: {owner: '', alias: ''},
    dnsas: {owner: '', alias: ''},
    elade: {owner: 'AS24 IT Elasticsearch', alias: 'Elastic Search'},
    elaki: {owner: 'AS24 IT Elasticsearch', alias: 'Kibana'},
    elans: {owner: 'AS24 IT Elasticsearch', alias: 'Elastic Search New Services'},
    elavm: {owner: 'AS24 IT Elasticsearch', alias: 'Elastic Search'},
    ftpdl: {owner: 'Gunnar Ludwig', alias: 'Delta FTP'},
    ftpma: {owner: '', alias: ''},
    ftpmp: {owner: '', alias: ''},
    haddb: {owner: 'Christian Schroer', alias: 'Hadoop'},
    hadfa: {owner: 'Christian Schroer', alias: 'Hadoop'},
    hadfe: {owner: 'Christian Schroer', alias: 'Hadoop'},
    hadff: {owner: 'Christian Schroer', alias: 'Hadoop'},
    hadhs: {owner: 'Christian Schroer', alias: 'Hadoop'},
    hadjs: {owner: 'Christian Schroer', alias: 'Hadoop'},
    hadmg: {owner: 'Christian Schroer', alias: 'Hadoop'},
    mgrsm: {owner: 'ASM Teams', alias: 'MongoDB ASM'},
    mondb: {owner: 'Sabine', alias: 'Dying, ask Sabine'},
    myqad: {owner: '', alias: 'MySQL'},
    myqar: {owner: '', alias: 'MySQL'},
    myqbt: {owner: '', alias: 'MySQL'},
    myqbx: {owner: '', alias: 'MySQL'},
    myqcm: {owner: '', alias: 'MySQL'},
    myqma: {owner: '', alias: 'MySQL Mobile Apps'},
    myqmd: {owner: '', alias: 'MySQL'},
    myqmt: {owner: '', alias: 'MySQL'},
    myqns: {owner: '', alias: 'MySQL'},
    myqst: {owner: '', alias: 'MySQL'},
    myqwp: {owner: '', alias: 'MySQL'},
    myqyt: {owner: '', alias: 'MySQL'},
    nfsbi: {owner: 'Richard Traebling', alias: 'Adeptia'},
    ntpas: {owner: '', alias: ''},
    oraad: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle ???'},
    orabi: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle ???'},
    oracr: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle ???'},
    oradw: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle ???'},
    oramd: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle ???'},
    oramg: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle ???'},
    oraob: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle ???'},
    orasb: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle Standby'},
    oratr: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle Tracking'},
    orats: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle Truckscout'},
    prxva: {owner: '', alias: ''},
    psqis: {owner: 'Sebastian Ullmann', alias: 'ISS'},
    pupdb: {owner: 'Michael Rauch', alias: 'Puppet DB'},
    puppb: {owner: 'Michael Rauch', alias: 'Puppet ???'},
    puppm: {owner: 'Michael Rauch', alias: 'Puppet Master'},
    rfsas: {owner: '', alias: ''},
    rmqas: {owner: '', alias: ''},
    rpccm: {owner: '', alias: ''},
    rpcgc: {owner: '', alias: ''},
    rpcla: {owner: '', alias: ''},
    sqlbi: {owner: 'Andreas Schmiedel', alias: 'BI Data Warehouse'},
    sqldy: {owner: '', alias: ''},
    sqltr: {owner: '', alias: ''},
    sshfp: {owner: '', alias: ''},
    talad: {owner: '', alias: ''},
    taldb: {owner: '', alias: ''},
    talex: {owner: '', alias: ''},
    terop: {owner: '', alias: ''},
    uxadm: {owner: '', alias: ''},
    webab: {owner: 'Vehicle Market Dealer', alias: 'MyArea', artifacts: '//dappbsv002/transfer/build_results/MyArea'},
    webac: {owner: '', alias: ''},
    webad: {owner: 'Manuela Moser', alias: 'ads.autoscout24.com'},
    webai: {owner: '', alias: ''},
    webal: {owner: '', alias: ''},
    webam: {owner: '', alias: ''},
    webap: {owner: '', alias: ''},
    webat: {owner: 'PrivateBuyer', alias: 'www.autoscout24.at'},
    webaw: {owner: '', alias: ''},
    webbe: {owner: 'PrivateBuyer', alias: 'www.autoscout24.be'},
    webbg: {owner: 'PrivateBuyer', alias: 'www.autoscout24.bg'},
    webct: {owner: '', alias: ''},
    webde: {owner: 'PrivateBuyer', alias: 'www.autoscout24.de'},
    webdi: {owner: 'Croatia', alias: 'DealerInfo'},
    weber: {owner: 'WebOps', alias: 'Error Server'},
    webes: {owner: 'PrivateBuyer', alias: 'www.autoscout24.es'},
    webew: {owner: '', alias: ''},
    webfa: {owner: 'PrivateBuyer', alias: 'CitySearch, Search'},
    webfb: {owner: '', alias: ''},
    webfr: {owner: 'PrivateBuyer', alias: 'www.autoscout24.fr'},
    webic: {owner: '', alias: ''},
    webid: {owner: 'CLM Team', alias: 'accounts.autoscout24.com', artifacts: '//dappbsv002/transfer/build_results/Identity'},
    webit: {owner: 'PrivateBuyer', alias: 'www.autoscout24.it'},
    webld: {owner: '', alias: ''},
    weblu: {owner: 'PrivateBuyer', alias: 'www.autoscout24.lu'},
    webnl: {owner: 'PrivateBuyer', alias: 'www.autoscout24.nl'},
    webns: {owner: '', alias: ''},
    webnw: {owner: '', alias: ''},
    webpl: {owner: 'PrivateBuyer', alias: 'www.autoscout24.pl'},
    webps: {owner: '', alias: ''},
    webro: {owner: 'PrivateBuyer', alias: 'www.autoscout24.ro'},
    webrp: {owner: 'CLM Team', alias: 'Identity Relying Party', artifacts: '//dappbsv002/transfer/build_results/Identity'},
    webrw: {owner: '', alias: ''},
    webse: {owner: '', alias: ''},
    websf: {owner: '', alias: ''},
    websm: {owner: 'ASM Teams', alias: 'Werkstattportal'},
    websw: {owner: '', alias: ''},
    webtp: {owner: '', alias: ''},
    webts: {owner: '', alias: ''},
    webtw: {owner: '', alias: ''},
    webvc: {owner: '', alias: ''},
    webws: {owner: 'VM', alias: 'WCF Web Services'},
}

require 'CSV'

def get_app_info(app)
  info = APP_INFO[app.to_s.downcase.to_sym]
  info || {owner: '', alias: ''}
end

def export_app_info(csv)
  CSV.open(csv, 'wb') do |csv|
    csv << %w(group owner alias artifacts)
    APP_INFO.each do |group, data|
      csv << [group, data[:owner], data[:alias], data[:artifacts]]
    end
  end
end

if $0 == __FILE__
  export_app_info(File.join(__dir__, 'AppOwner.csv'))
end