
APP_INFO = {
    admad: {owner: '', alias: ''},
    admas: {owner: '', alias: ''},
    admsm: {owner: '', alias: ''},
    appad: {owner: '', alias: ''},
    appai: {owner: '', alias: ''},
    appar: {owner: '', alias: ''},
    appba: {owner: '', alias: ''},
    appbd: {owner: '', alias: ''},
    appbi: {owner: '', alias: ''},
    appbr: {owner: '', alias: ''},
    appbs: {owner: '', alias: ''},
    appbt: {owner: '', alias: ''},
    appbx: {owner: '', alias: ''},
    appcm: {owner: '', alias: ''},
    appdj: {owner: '', alias: ''},
    appdl: {owner: 'WebOps', alias: 'TruckScout Delta'},
    appds: {owner: '', alias: 'AS24 Delta'},
    appdw: {owner: '', alias: ''},
    appdy: {owner: '', alias: ''},
    appia: {owner: '', alias: ''},
    appib: {owner: '', alias: ''},
    appis: {owner: '', alias: ''},
    appjo: {owner: '', alias: ''},
    appjs: {owner: '', alias: ''},
    appkm: {owner: '', alias: ''},
    appl7: {owner: '', alias: ''},
    appld: {owner: '', alias: ''},
    appma: {owner: '', alias: ''},
    appmd: {owner: '', alias: ''},
    appmj: {owner: '', alias: ''},
    appms: {owner: '', alias: ''},
    appmw: {owner: '', alias: ''},
    appnj: {owner: '', alias: ''},
    apppj: {owner: '', alias: ''},
    apppp: {owner: '', alias: ''},
    appre: {owner: '', alias: ''},
    apprw: {owner: '', alias: ''},
    appsat: {owner: '', alias: ''},
    appsf: {owner: '', alias: ''},
    appsm: {owner: '', alias: ''},
    appst: {owner: '', alias: ''},
    apptj: {owner: '', alias: ''},
    appvo: {owner: '', alias: ''},
    appwp: {owner: '', alias: ''},
    appwt: {owner: '', alias: ''},
    appwu: {owner: '', alias: ''},
    appxf: {owner: '', alias: ''},
    appyt: {owner: '', alias: ''},
    bakpu: {owner: '', alias: ''},
    cdncp: {owner: '', alias: ''},
    cdncs: {owner: '', alias: ''},
    cdnds: {owner: '', alias: ''},
    cdnpi: {owner: '', alias: 'Picture Server'},
    cdnsc: {owner: 'Christian Rodemeyer', alias: 's.autoscout24.de', artifacts: '//dappbsv002/transfer/build_results/s.autoscout24.de'},
    cdnws: {owner: '', alias: ''},
    dcoas: {owner: '', alias: ''},
    dcoli: {owner: '', alias: ''},
    dcoop: {owner: '', alias: ''},
    dcosv: {owner: '', alias: ''},
    dcows: {owner: '', alias: ''},
    dnsas: {owner: '', alias: ''},
    elade: {owner: '', alias: ''},
    elaki: {owner: 'AS24 IT Elasticsearch', alias: 'Kibana'},
    elans: {owner: '', alias: ''},
    elavm: {owner: 'AS24 IT Elasticsearch', alias: 'Elastic Search'},
    ftpdl: {owner: 'Delta Team', alias: 'Delta FTP'},
    ftpma: {owner: '', alias: ''},
    ftpmp: {owner: '', alias: ''},
    haddb: {owner: '', alias: ''},
    hadfa: {owner: '', alias: ''},
    hadfe: {owner: '', alias: ''},
    hadff: {owner: '', alias: ''},
    hadhs: {owner: '', alias: ''},
    hadjs: {owner: '', alias: ''},
    hadmg: {owner: '', alias: ''},
    mgrsm: {owner: '', alias: ''},
    mondb: {owner: '', alias: ''},
    myqad: {owner: '', alias: ''},
    myqar: {owner: '', alias: ''},
    myqbt: {owner: '', alias: ''},
    myqbx: {owner: '', alias: ''},
    myqcm: {owner: '', alias: ''},
    myqma: {owner: '', alias: ''},
    myqmd: {owner: '', alias: ''},
    myqmt: {owner: '', alias: ''},
    myqns: {owner: '', alias: ''},
    myqst: {owner: '', alias: ''},
    myqwp: {owner: '', alias: ''},
    myqyt: {owner: '', alias: ''},
    nfsbi: {owner: '', alias: ''},
    ntpas: {owner: '', alias: ''},
    oraad: {owner: '', alias: ''},
    orabi: {owner: '', alias: ''},
    oracr: {owner: '', alias: ''},
    oradw: {owner: '', alias: ''},
    oramd: {owner: '', alias: ''},
    oramg: {owner: '', alias: ''},
    oraob: {owner: 'AS24 IT DB Admin Oracle', alias: ''},
    orasb: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle Standby'},
    oratr: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle Tracking'},
    orats: {owner: 'AS24 IT DB Admin Oracle', alias: 'Oracle Truckscout'},
    prxva: {owner: '', alias: ''},
    psqis: {owner: '', alias: ''},
    pupdb: {owner: '', alias: ''},
    puppb: {owner: '', alias: ''},
    puppm: {owner: '', alias: ''},
    rfsas: {owner: '', alias: ''},
    rmqas: {owner: '', alias: ''},
    rpccm: {owner: '', alias: ''},
    rpcgc: {owner: '', alias: ''},
    rpcla: {owner: '', alias: ''},
    sqlbi: {owner: '', alias: ''},
    sqldy: {owner: '', alias: ''},
    sqltr: {owner: '', alias: ''},
    sshfp: {owner: '', alias: ''},
    talad: {owner: '', alias: ''},
    taldb: {owner: '', alias: ''},
    talex: {owner: '', alias: ''},
    terop: {owner: '', alias: ''},
    uxadm: {owner: '', alias: ''},
    webab: {owner: 'Vehicle Market Dealer', alias: 'MyArea', artifacts: '//dappbsv002/transfer/build_results/MyArea'},
    webac: {owner: '', alias: ''},
    webad: {owner: 'Manuela Moser', alias: 'ads.autoscout24.com'},
    webai: {owner: '', alias: ''},
    webal: {owner: '', alias: ''},
    webam: {owner: '', alias: ''},
    webap: {owner: '', alias: ''},
    webat: {owner: 'PrivateBuyer', alias: 'www.autoscout24.at'},
    webaw: {owner: '', alias: ''},
    webbe: {owner: 'PrivateBuyer', alias: 'www.autoscout24.be'},
    webbg: {owner: 'PrivateBuyer', alias: 'www.autoscout24.bg'},
    webct: {owner: '', alias: ''},
    webde: {owner: 'PrivateBuyer', alias: 'www.autoscout24.de'},
    webdi: {owner: 'Croatia', alias: 'DealerInfo'},
    weber: {owner: 'WebOps', alias: 'Error Server'},
    webes: {owner: 'PrivateBuyer', alias: 'www.autoscout24.es'},
    webew: {owner: '', alias: ''},
    webfa: {owner: '', alias: ''},
    webfb: {owner: '', alias: ''},
    webfr: {owner: 'PrivateBuyer', alias: 'www.autoscout24.fr'},
    webic: {owner: '', alias: ''},
    webid: {owner: 'CLM', alias: 'accounts.autoscout24.com'},
    webit: {owner: 'PrivateBuyer', alias: 'www.autoscout24.it'},
    webld: {owner: '', alias: ''},
    weblu: {owner: 'PrivateBuyer', alias: 'www.autoscout24.lu'},
    webnl: {owner: 'PrivateBuyer', alias: 'www.autoscout24.nl'},
    webns: {owner: '', alias: ''},
    webnw: {owner: '', alias: ''},
    webpl: {owner: 'PrivateBuyer', alias: 'www.autoscout24.pl'},
    webps: {owner: '', alias: ''},
    webro: {owner: 'PrivateBuyer', alias: 'www.autoscout24.ro'},
    webrp: {owner: '', alias: ''},
    webrw: {owner: '', alias: ''},
    webse: {owner: '', alias: ''},
    websf: {owner: '', alias: ''},
    websm: {owner: '', alias: ''},
    websw: {owner: '', alias: ''},
    webtp: {owner: '', alias: ''},
    webts: {owner: '', alias: ''},
    webtw: {owner: '', alias: ''},
    webvc: {owner: '', alias: ''},
    webws: {owner: 'VM', alias: 'WCF Web Services'},
}

def get_app_info(app)
  info = APP_INFO[app.to_s.downcase.to_sym]
  info || {owner: '', alias: ''}
end

if $0 == __FILE__
  require 'CSV'
  CSV.open('app_info.csv', 'wb') do |csv|
    csv << %w(group owner alias artifacts)
    APP_INFO.each do |group, data|
      csv << [group, data[:owner], data[:alias], data[:artifacts]]
    end
  end
end